### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ethanaobrien** [llsif-waifu-sim/llsif-waifu-sim.github.io#1]
Could you like make a new repository where all of the files are edited to work 100% offline? It would be really helpful for me.

Thanks!

**Comment by vanstorm9** [comment]
Hello, sorry for the late response, had a lot of things going on.

Do you mind telling me which links are broken? I would like to update the site to fix those issues. 

Also it is very easy to have this repo work offline. 

Take a look at here on line 99 and 183. Those are links to the actual files being used from an online repo. All you have to do is just change those URLs to a local path on your computer.
https://github.com/llsif-waifu-sim/llsif-waifu-sim.github.io/blob/master/js/audio-handle.js

Does this answer your question?

**Comment by ethanaobrien** [comment]
@vanstorm9 Yes, this was the answer I was looking for. Thank you!
