### ISSUE TITLE
Interest

### ISSUE THREAD

**Issue by 641i130** [llsif-waifu-sim/llsif-waifu-sim.github.io#2]
How'd you all get all these files :joy: ? I'm interested in helping. Did you just decrypt the game assets?

**Comment by ethanaobrien** [comment]
@641i130 

I made a tool that will download the cards. This might help. https://github.com/ethanaobrien/sif-card-downloader

**Comment by 641i130** [comment]
This is amazing! Ive been trying to document the Llsif api the app uses but I've had trouble starting. I think I just need to sit down and get started.

**Comment by vanstorm9** [comment]
So the scripts on this repo retrieves game assets that are hosted on various sources online (either API request or pure web scraping) which are then downloaded to assigned locations.

If you are interested in helping, feel free to reach out here:
llsif.waifu.sim@gmail.com
